language: ruby
cache: bundler
os: linux
addons:
  chrome: stable
  apt:
    packages:
      - libcurl4-openssl-dev
before_install:
  - gem update --system
  - gem install bundler
script: xvfb-run bundle exec rake
notifications:
  webhooks: https://www.travisbuddy.com/
  on_success: never
jobs:
  include:
    - name: "Test Brewfile"
      language: generic
      os: osx
      before_script: brew bundle --file=files/.Brewfile
