brew 'ack'
brew 'awscli'
brew 'git'
brew 'htop'
brew 'macvim'
brew 'mas'
brew 'nmap'
brew 'pipenv'
brew 'pyenv'
brew 'rbenv'
brew 'tmux'
brew 'vim'
brew 'wget'
cask 'android-studio'
cask 'atom'
cask 'authy'
cask 'aws-vault'
cask 'cyberduck'
cask 'docker'
cask 'dupeguru'
cask 'flycut'
cask 'gimp'
cask 'google-chrome'
cask 'google-cloud-sdk'
cask 'gpg-suite'
cask 'hdhomerun'
cask 'homebrew/cask-drivers/uhk-agent'
cask 'iterm2'
cask 'keybase'
cask 'libreoffice'
cask 'macdown'
cask 'mactex'
cask 'meld'
cask 'nightowl'
cask 'rectangle'
cask 'sekey'
cask 'spectacle'
cask 'vlc'
cask 'windscribe'
cask 'zoomus'
mas 'Amphetamine', id: 937984704
mas 'Slack', id: 803453959
mas 'Telegram Desktop', id: 946399090
mas 'Trello', id: 1278508951
mas 'WhatsApp', id: 1147396723
mas 'Xcode', id: 497799835
