name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: nanasess/setup-chromedriver@master
    - name: Set up RVM
      run: |
        curl -sSL https://get.rvm.io | bash

    - name: Set up Ruby from .ruby-version
      run: |
        source $HOME/.rvm/scripts/rvm
        rvm install $(cat .ruby-version) --binary
        rvm --default use $(cat .ruby-version)
        gem update --system
    - name: Run a multi-line script
      run: |
        sudo apt-get install xvfb
        export DISPLAY=:99
        source $HOME/.rvm/scripts/rvm
        bundle install --jobs 4 --retry 3
        sudo xvfb bundle exec rake
