name: CI

on:
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 1 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: nanasess/setup-chromedriver@master
    - name: Setup env
      run: |
        echo "::add-path::$HOME/.rbenv/bin"
        echo "::add-path::$HOME/.rbenv/shims"
        echo "::add-path::$HOME/.tfenv/bin"
    - name: Set up rbenv
      run: |
        curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-installer | bash
    - name: Install tfenv
      run: git clone https://github.com/tfutils/tfenv.git ~/.tfenv
    - name: Test tfenv
      run: |
        tfenv install
        terraform fmt
    - name: terraform plan
      env:
        DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
        DATADOG_APP_KEY: ${{ secrets.DATADOG_APP_KEY }}
      run: terraform plan
    - name: Run a multi-line script
      run: |
        export DISPLAY=:99
        bundle install --jobs 4 --retry 3
        xvfb-run bundle exec rake
