name: CI

on:
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 1 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: nanasess/setup-chromedriver@master
    - name: Set up rbenv
      run: brew install rbenv tfenv
    - name: Setup env
      run: |
        echo "::add-path::$HOME/.rbenv/bin"
        echo "::add-path::$HOME/.rbenv/shims"
        echo "::add-path::$HOME/.tfenv/bin"
    - name: Test tfenv
      run: |
        terraform fmt
    - name: terraform init and plan
      env:
        DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
        DATADOG_APP_KEY: ${{ secrets.DATADOG_APP_KEY }}
      run: terraform init && terraform plan
    - name: Run a multi-line script
      run: |
        export DISPLAY=:99
        sudo gem install bundler
        bundle install --jobs 4 --retry 3
        xvfb-run bundle exec rake
