name: CI

on:
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 1 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: nanasess/setup-chromedriver@master
    - name: Run brewfile
      # TODO https://github.com/Homebrew/linuxbrew-core/issues/20914
      run: sudo ln -s /usr/include/locale.h /usr/include/xlocale.h && brew bundle
    - name: Setup env
      run: |
        echo "::add-path::$HOME/.rbenv/bin"
        echo "::add-path::$HOME/.rbenv/shims"
        echo "::add-path::$HOME/.tfenv/bin"
    - name: terraform fmt
      run: terraform fmt -diff -check
    - name: Run a multi-line script
      run: |
        export DISPLAY=:99
        sudo gem install bundler
        bundle install --jobs 4 --retry 3
        xvfb-run bundle exec rake
