name: CI

on:
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 1 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: nanasess/setup-chromedriver@master
    - name: Set up RVM
      run: |
        curl -sSL https://get.rvm.io | bash
    - name: Install tfenv
      run: |
        git clone https://github.com/tfutils/tfenv.git ~/.tfenv
        echo "::add-path::$HOME/.tfenv/bin:$PATH"
    - name: Test tfenv
      run: |
        tfenv install
        terraform fmt
    - name: Set up Ruby from .ruby-version
      run: |
        source $HOME/.rvm/scripts/rvm
        rvm install $(cat .ruby-version) --binary
        rvm --default use $(cat .ruby-version)
        gem update --system
    - name: Run a multi-line script
      run: |
        export DISPLAY=:99
        source $HOME/.rvm/scripts/rvm
        bundle install --jobs 4 --retry 3
        xvfb-run bundle exec rake
