name: CI

on:
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 1 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: nanasess/setup-chromedriver@v1.0.5
    - uses: actions/cache@v2
      with:
        path: ~/.rbenv/versions
        key: ${{ runner.os }}-rbenv-${{ hashFiles('.ruby-version') }}
        restore-keys: |
          ${{ runner.os }}-rbenv-
    - name: Run brewfile
      run: brew bundle
    - name: terraform fmt
      run: tfenv install && terraform fmt -diff -check
    - name: Run a multi-line script
      env:
        DISPLAY: :99
      run: |
        eval "$(rbenv init -)"
        rbenv install --skip-existing
        gem install bundler
        bundle install
        xvfb-run bundle exec rake
