name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install RVM
      run: \curl -sSL https://get.rvm.io | bash -s stable
    - name: Install Ruby version using RVM
      run: rvm use $(< .ruby-version) --install --binary --fuzzy
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
