name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install RVM
      run: |
      gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
      \curl -sSL https://get.rvm.io | bash -s stable
    - name: Install Ruby version using RVM
      run: rvm use $(< .ruby-version) --install --binary --fuzzy
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
