name: CI

on:
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 1 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: nanasess/setup-chromedriver@master
    - name: Set up rbenv
      run: |
        echo "::add-path::$HOME/.rbenv/bin:$PATH"
        curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-installer | bash
    - name: Install tfenv
      run: |
        git clone https://github.com/tfutils/tfenv.git ~/.tfenv
        echo "::add-path::$HOME/.tfenv/bin:$PATH"
    - name: Test tfenv
      run: |
        tfenv install
        terraform fmt
    - name: Set up Ruby from .ruby-version
      run: |
        gem update --system
    - name: Run a multi-line script
      run: |
        export DISPLAY=:99
        bundle install --jobs 4 --retry 3
        xvfb-run bundle exec rake
